
package introsde.rest.activitypreference.soap.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "General", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface General {


    /**
     * 
     * @param personId
     * @return
     *     returns java.util.List<introsde.rest.activitypreference.soap.ws.Suggestion>
     * @throws JsonParseException_Exception
     * @throws JsonMappingException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "")
    @RequestWrapper(localName = "getMySuggestion", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/", className = "introsde.rest.activitypreference.soap.ws.GetMySuggestion")
    @ResponseWrapper(localName = "getMySuggestionResponse", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/", className = "introsde.rest.activitypreference.soap.ws.GetMySuggestionResponse")
    @Action(input = "http://ws.soap.activitypreference.rest.introsde/General/getMySuggestionRequest", output = "http://ws.soap.activitypreference.rest.introsde/General/getMySuggestionResponse", fault = {
        @FaultAction(className = JsonParseException_Exception.class, value = "http://ws.soap.activitypreference.rest.introsde/General/getMySuggestion/Fault/JsonParseException"),
        @FaultAction(className = JsonMappingException_Exception.class, value = "http://ws.soap.activitypreference.rest.introsde/General/getMySuggestion/Fault/JsonMappingException"),
        @FaultAction(className = IOException_Exception.class, value = "http://ws.soap.activitypreference.rest.introsde/General/getMySuggestion/Fault/IOException")
    })
    public List<Suggestion> getMySuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId)
        throws IOException_Exception, JsonMappingException_Exception, JsonParseException_Exception
    ;

    /**
     * 
     * @param personId
     * @return
     *     returns introsde.rest.activitypreference.soap.ws.Suggestion
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "")
    @RequestWrapper(localName = "calculateSuggestion", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/", className = "introsde.rest.activitypreference.soap.ws.CalculateSuggestion")
    @ResponseWrapper(localName = "calculateSuggestionResponse", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/", className = "introsde.rest.activitypreference.soap.ws.CalculateSuggestionResponse")
    @Action(input = "http://ws.soap.activitypreference.rest.introsde/General/calculateSuggestionRequest", output = "http://ws.soap.activitypreference.rest.introsde/General/calculateSuggestionResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://ws.soap.activitypreference.rest.introsde/General/calculateSuggestion/Fault/IOException")
    })
    public Suggestion calculateSuggestion(
        @WebParam(name = "personId", targetNamespace = "")
        int personId)
        throws IOException_Exception
    ;

    /**
     * 
     * @param suggestion
     */
    @WebMethod
    @RequestWrapper(localName = "postSuggestion", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/", className = "introsde.rest.activitypreference.soap.ws.PostSuggestion")
    @ResponseWrapper(localName = "postSuggestionResponse", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/", className = "introsde.rest.activitypreference.soap.ws.PostSuggestionResponse")
    @Action(input = "http://ws.soap.activitypreference.rest.introsde/General/postSuggestionRequest", output = "http://ws.soap.activitypreference.rest.introsde/General/postSuggestionResponse")
    public void postSuggestion(
        @WebParam(name = "suggestion", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Suggestion> suggestion);

}
