
package introsde.rest.activitypreference.soap.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JsonParseException", targetNamespace = "http://ws.soap.activitypreference.rest.introsde/")
public class JsonParseException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JsonParseException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public JsonParseException_Exception(String message, JsonParseException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public JsonParseException_Exception(String message, JsonParseException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: introsde.rest.activitypreference.soap.ws.JsonParseException
     */
    public JsonParseException getFaultInfo() {
        return faultInfo;
    }

}
